### ISSUE TITLE
v1.0.0: 'faCheck' is not exported by node_modules/@fortawesome/free-solid-svg-icons/index.js

### ISSUE THREAD

**Issue by st-h** [FortAwesome/ember-fontawesome#230]
**Describe the bug**
Upgrade ember-fonteawesome to 1.0.0 together with `@fortawesome/free-solid-svg-icons: 5.15.4` and an icon.js config.
When running an ember 4.12.0 app,  the following error is printed:

```
'faCheck' is not exported by ../../../../../../../../Users/steve/code/myapp/node_modules/@fortawesome/free-solid-svg-icons/index.js, imported by exports-free-solid-svg-icons.js
```

Rolling back to 0.4.2 and everything works fine again. However, the changelog says that there were no changes between 0.4.2 and 1.0.0 🤷‍♀️ I have deleted my node_modules folder, to make sure this is not a local issue, but the issue persists repeatedly.

yarn version: 1.22.19

**Expected behavior**
The app still boots up after upgrading to v1.0.0.

**Comment by Techn1x** [comment]
Exactly the same issue for me, though the icon changes depending on the project.
`faCalendar` on one project, `faSort` on another.

It always seems to be the first icon listed in icons.js

---

It looks like the broccoli-rollup v5 bump seemed to be published under the v1 FA update instead of the v0.4.2 update, as the commit history & changelog for this project would suggest.

Given that publishing mixup, it's likely that something to do with FA's implementation of broccoli-rollup v5 causing the issues here.

Here's a diff of 0.4.1 to 0.4.2....... broccoli-rollup version does not seem to change.
![image](https://github.com/FortAwesome/ember-fontawesome/assets/1049837/f9d063d5-bdb4-4ece-9bac-c7c68579c235)

![image](https://github.com/FortAwesome/ember-fontawesome/assets/1049837/9c1014f9-8526-4426-a86d-ab765c08133c)

**Comment by Techn1x** [comment]
Friendly ping to @robmadole - might need some patch releases...
- 0.4.3 that actually does the broccoli-rollup v5 bump, & ideally a fix for whatever is causing the above build errors
- 1.0.1 with a patch for the above as well

**Comment by Techn1x** [comment]
As with the OP, I am also running this with `@fortawesome/free-solid-svg-icons: 5.15.4`

From what I can tell, we need the exports to be listed in the package.json files of the icon packages. It's given in v6 but not v5
https://github.com/FortAwesome/Font-Awesome/blob/0698449d50f2b95517562295a59d414afc68b369/js-packages/@fortawesome/free-regular-svg-icons/package.json#L34-L51

The broccoli-rollup PR author mentions this too.
https://github.com/FortAwesome/ember-fontawesome/pull/229#issue-1682621325

I hope this gives enough to go on

**Comment by robmadole** [comment]
Ok, I'll take another look at this as soon as I can. Thanks, all.

**Comment by robmadole** [comment]
Alright folks. I've just released 0.4.3 and I think it contains the updates that I missed in 0.4.2.

If anyone has time to test it and let me know that would be appreciated. Thanks @Techn1x for the oversight.

**Comment by Techn1x** [comment]
Thanks for that release - do you know who would be best to ping about updating the v5 icon packages to work with broccoli-rollup v5 ?

**Comment by robmadole** [comment]
@Techn1x thats us! We are only updating the 5.x line for security patches though so that fix won't get prioritized. We're recommending everyone upgrade to major version 6.

**Comment by Techn1x** [comment]
> We are only updating the 5.x line for security patches

Website would disagree with you there.. might want to update it if that's the case.
https://fontawesome.com/versions
![image](https://github.com/FortAwesome/ember-fontawesome/assets/1049837/96149154-9926-4477-9e29-45cf483cdae9)

> We're recommending everyone upgrade to major version 6.

Of course. But I guess anyone on the v5 icon set won't get to be able to be use ember-fontawesome v1 "stable", which is a bit rough. Was only a year and a bit ago when v6 icons weren't even released yet.

I understand old releases can't be maintained forever, but I did expect a little higher out of an LTS for an icon set where updating changes the look and feel of a website. It does shine a light on the fact that a downside of using an icon framework like this means the icons are going to change else the code will be left behind.

I also wonder if [react-fontawesome](https://github.com/FortAwesome/react-fontawesome) still works with the v5 icon set...

**Comment by mkszepp** [comment]
@robmadole `v0.4.3` is still broken with FA5. Versions <= `v0.4.2` are working with FA5. Already tried to make a clean install

```js
Build Error (pro-solid-svg-icons-rollup)

'faAngleRight' is not exported by ../../../../home/myuser/projects/my-project/node_modules/@fortawesome/pro-solid-svg-icons/index.js, imported by exports-pro-solid-svg-icons.js
```

For me FA5 is also still a LTS Version.. also in the download-Page there is written, so i think, that this packages should also support FA5.
![grafik](https://github.com/FortAwesome/ember-fontawesome/assets/19845290/7506c47b-2d6a-4f20-aefe-fb35a6928474)

**Comment by st-h** [comment]
> @Techn1x thats us! We are only updating the 5.x line for security patches though so that fix won't get prioritized. We're recommending everyone upgrade to major version 6.

@robmadole Believe me, I would love to upgrade to version 6 so much, but at the current stage some (especially duotone) icons are in, it is pretty much impossible to do so without confusing our users. For instance, this is used to be an envelope, but it now just looks like an odd geometrical shape. Could you please either fix v6, or continue to maintain v5? That would be super awesome. Thank you.

<img width="468" alt="Screenshot 2023-06-14 at 17 08 14" src="https://github.com/FortAwesome/ember-fontawesome/assets/5768353/8a2d5178-595a-42ed-af07-1531cd942eca">

Another alternative probably would be to implement #195 and allow users to create kits that mix v5 and v6 icons, so we can keep the v5 icons that are better quality than v6 icons. But that probably would still mean to continue to support v5.

**Comment by robmadole** [comment]
> @Techn1x Website would disagree with you there.. might want to update it if that's the case.

Fair point. We either need to stand by that or change it. We'll give this some thought.

> I understand old releases can't be maintained forever, but I did expect a little higher out of an LTS for an icon set where updating changes the look and feel of a website. It does shine a light on the fact that a downside of using an icon framework like this means the icons are going to change else the code will be left behind.

We haven't thought of it from this point of view much. The idea that changing the look of the icon is considered a major change is a bit of a surprise. This is probably because of internal bias (6 is better!) and underestimating how much some of the icons have changed (as @st-h has mentioned).

> @mkszepp v0.4.3 is still broken with FA5.

I was not aware! That changes some of my thinking on this.

I'll need to think through these points. Thanks everyone for spending the time. I'll comment back here when we make a decision.

**Comment by Techn1x** [comment]
Hi @robmadole - any update on this ?

> I also wonder if [react-fontawesome](https://github.com/FortAwesome/react-fontawesome) still works with the v5 icon set...

Answering my own question - it does seem to build with v5 icon set. Ideally ember-fontawesome shouldn't be any different..
https://github.com/FortAwesome/react-fontawesome/blob/976c1adc59934b34e52b11c03dda4bd69831a6df/package.json#L61C4-L61C52

**Comment by jrjohnson** [comment]
The best way to maintain support for v5 icons is to pin this add-on at `0.4.2` in your package.json. Now that we have a 1.0 release it will be easier for us to be clear about breaking changes and pay more attention to details like this. At this point it seems that pinning that release is the easiest way to get support for the older FA package which isn't structured correctly.

**Comment by Techn1x** [comment]
EDIT: looks like there has been movement on keeping FA5 working 🎉   Will leave my original comment as is, below

---

Pinning this addon to 0.4.2 with its ancient versions of dependencies forever is exactly what I want to avoid..

Disappointing but I've already made my case and I'll that's all I can do

I don't really see the problem as being ember-fontawesome here -  it didn't/doesn't promise any kind of LTS and wasn't a stable 1.0 version yet. But rather the FA v5 LTS icon set does promise quality of life fixes / patch updates - IMO the fix needed here would be exactly that. I am guessing it must be a huge PITA to fix given that maintainers seem to be against it.

Might want to update the readme and github about sections for its various references to FA 5 (and even 4)..
> Font Awesome 5 Ember component using SVG with JS

It would be extra kind to consumers to update the changelog too with the now-known breaking changes ❤️
